# Basic Site Configuration
baseURL: 'https://profincognito.me/'
languageCode: 'en-us'
title: 'Professor Incognito'
theme: 'hugo-WonderMod'
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'

# Primary Parameters
params:
  # Theme Settings
  defaultTheme: dark
  ShowReadingTime: true
  ShowToc: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  # Enhanced Meta Tags - Minimal but Effective
  description: "Privacy Researcher & Security Strategist | FIDE Arena Grand Master"
  images: 
    - "/images/site-feature-image.webp"
  
  # Open Graph - Essential Only
  opengraph: true
  og:
    type: "website"
    title: "Professor Incognito"
    description: "Privacy Researcher & Security Strategist | FIDE Arena Grand Master"
    image: "/images/site-feature-image.webp"
    siteName: "Professor Incognito"

  # Twitter Cards - Minimal
  twitter:
    card: "summary_large_image"
    site: "@iAnonymous3000"
    image: "/images/site-feature-image.webp"
    
  # Schema.org - Professional Focus
  schema:
    type: "Person"
    name: "Professor Incognito"
    jobTitle: "Privacy Researcher & Security Strategist"
    url: "https://profincognito.me"
    image: "/images/site-feature-image.webp"
    award: "FIDE Arena Grand Master"

  # Balanced Security Headers
  securityHeaders:
    contentSecurityPolicy: >-
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://avatars.githubusercontent.com https://*.githubusercontent.com;
      font-src 'self' data:;
      connect-src 'self' https://cloudflareinsights.com;
      frame-src 'self' https://www.youtube-nocookie.com;
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      upgrade-insecure-requests;
      block-all-mixed-content;
    xFrameOptions: "DENY"
    xContentTypeOptions: "nosniff"
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: >-
      accelerometer=(),
      camera=(),
      geolocation=(),
      microphone=(),
      payment=(),
      usb=()
    strictTransportSecurity: "max-age=31536000; includeSubDomains"

  # Balanced Privacy Settings
  privacy:
    disableFingerprinting: true
    cloudflare:
      enable: true
    googleAnalytics:
      disable: true
    instagram:
      disable: true
    youtube:
      disable: false
      privacyEnhanced: true
    twitter:
      disable: false
      enableDNT: true

  # Asset Configuration
  assets:
    disableFingerprinting: true
    favicon: "/images/favicon.ico"
    imageOptimization:
      enable: true
      formats: ["webp"]
      quality: 85
    lazyLoading: true

  # Homepage Configuration
  profileMode:
    enabled: true
    title: "Professor Incognito"
    subtitle: "Privacy Researcher & Security Strategist | FIDE Arena Grand Master"
    imageUrl: "https://avatars.githubusercontent.com/u/32236127?v=4"
    buttons:
      - name: Portfolio
        url: "https://linksta.cc/@ianonymous3000"

  # Social Links with Privacy Protection
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/soorajsathyanarayanan"
      params:
        rel: "noopener noreferrer"
    - name: twitter
      url: "https://x.com/iAnonymous3000"
      params:
        rel: "noopener noreferrer"
    - name: github
      url: "https://github.com/iAnonymous3000"
      params:
        rel: "noopener noreferrer"
    - name: mastodon
      url: "https://mastodon.social/@ianonymous3000"
      params:
        rel: "me noopener noreferrer"

  # Cloudflare Settings
  cloudflare:
    analytics: true
    cacheTTL: "4h"
    alwaysUseHTTPS: true
    minify:
      html: true
      css: true
      js: true

# Output Settings
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML

# Enhanced Robot Control
enableRobotsTXT: true
robotsTXT: |
  User-agent: *
  Disallow: /private/
  Disallow: /search/
  Disallow: /cdn-cgi/
  Allow: /posts/
  Allow: /research/
  Allow: /projects/
  Allow: /chess/
  Sitemap: https://profincognito.me/sitemap.xml

# Navigation Menu
menu:
  main:
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 10
    - identifier: research
      name: Research
      url: /research/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: chess
      name: Chess
      url: /chess/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50

# Syntax Highlighting
markup:
  highlight:
    style: dracula
    noClasses: false
    guessSyntax: true
