baseURL: 'https://profincognito.me/'
languageCode: 'en-us'
title: 'Professor Incognito'
theme: 'hugo-WonderMod'

params:
  defaultTheme: dark
  ShowReadingTime: true
  ShowToc: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  # Custom Colors & Font (Accessibility improvements)
  primaryColor: "#3498db"  # Ensure high contrast for readability
  secondaryColor: "#2c3e50"  # Ensure high contrast
  font: "'Segoe UI', 'Helvetica Neue', Arial, sans-serif"  # Updated font stack for consistency

  # Custom CSS (Minified for performance)
  customCSS: "/assets/css/custom.min.css"

  # Homepage Configuration
  profileMode:
    enabled: true
    title: "Sooraj Sathyanarayanan"
    subtitle: "Privacy Researcher & Security Strategist | FIDE Arena Grand Master"
    imageUrl: "static/images/profile-pic_memoji.jpg"
    buttons:
      - name: "Research"
        url: "/research/"
      - name: "Security Blog"
        url: "/posts/"
      - name: "Open Source"
        url: "/projects/"
      - name: "Chess & Security"
        url: "/chess/"
      - name: "Support Privacy"
        url: "/donate/"

  # Social & Contact
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/sooraj-sathyanarayanan"
    - name: twitter
      url: "https://x.com/iAnonymous3000"
    - name: github
      url: "https://github.com/iAnonymous3000"
    - name: mastodon
      url: "https://mastodon.social/@ianonymous3000"
  

  # Privacy Enhancements
  privacy:
    disableFingerprinting: true  
    googleAnalytics:
      disable: true
    twitter:
      disable: false  # Enabled to display Twitter/X content
    instagram:
      disable: true
    youtube:
      disable: false

  # Security Headers (Enhance security)
  securityHeaders:
    contentSecurityPolicy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';"
    xFrameOptions: "DENY"
    xContentTypeOptions: "nosniff"
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: "geolocation=(), microphone=()"

  # Search Configuration
  search:
    enable: true
    type: "fuse"

  # Assets Configuration (Performance improvements)
  assets:
    disableFingerprinting: true  
    favicon: "/images/favicon.ico"
    imageOptimization:
      enable: true
      formats: ["webp"]  # Use modern image formats
      quality: 85
    lazyLoading: true  # Implement lazy loading for images

  # Accessibility Enhancements
  accessibility:
    enableARIA: true  # Custom parameter to enable ARIA labels
    keyboardNavigation: true  # Ensure site is navigable via keyboard

menu:
  main:
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 10
    - identifier: research
      name: Research
      url: /research/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: chess
      name: Chess
      url: /chess/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50

markup:
  highlight:
    style: dracula
    noClasses: false
    guessSyntax: true



